image: docker:stable
services:
  - docker:dind

stages:
- build
- test
- release
- deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REVISION: 1
  DOCKER_VERSION: "18.04"
  DOCKER_HEALTHCHECK_TIMEOUT: "60"
  CONTAINER_TEST_IMAGE: registry.gitlab.com/gamefield/noswings/server/world:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/gamefield/noswings/server/world:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build_docker:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  tags:
    - docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master