services:
  - docker:dind

stages:
- build
- test
- release
- deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  REVISION: 1
  DOCKER_VERSION: "18.04"
  DOCKER_HEALTHCHECK_TIMEOUT: "60"
  CONTAINER_REGISTRY: registry.gitlab.com/gamefield/saltynos/Server/World
  CONTAINER_WORLD_BUILD_IMAGE: $CONTAINER_REGISTRY/saltyemu-world:$CI_BUILD_REF_NAME
  CONTAINER_WORLD_RELEASE_IMAGE: $CONTAINER_REGISTRY/saltyemu-world:latest

 
build_project:
  image: microsoft/dotnet:2.1-sdk-alpine
  stage: build
  script:
   - dotnet restore
   - dotnet build
   
   
test_project:
    image: microsoft/dotnet:2.1-sdk-alpine
    stage: test
    script:
    - dotnet restore
    - dotnet test test/ChickenAPI.Game.Test/


# Docker Building
build_docker:
  stage: build
  image: docker:stable
  tags:
    - docker
  only:
    - tags
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build -t $CONTAINER_WORLD_BUILD_IMAGE world/
    - docker push $CONTAINER_WORLD_BUILD_IMAGE

# Docker Building ${docker}:latest
# master branch only
release_docker:
  stage: release
  image: docker:stable
  tags:
    - docker
  only:
    - master
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build -t $CONTAINER_WORLD_RELEASE_IMAGE world/
    - docker push $CONTAINER_WORLD_RELEASE_IMAGE
  dependencies:
    - build_docker